//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocksmithToolkitGUI.CGM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resCGM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resCGM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocksmithToolkitGUI.CGM.resCGM", typeof(resCGM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;urn:uuid:%RDM13%-3f6b-e531-4ae1-%RDM2%%RDM3%&gt; &lt;http://emergent.net/aweb/1.0/name&gt; &quot;guitar_%guitarnamesix%&quot;.
        ///
        ///
        ///
        ///&lt;urn:uuid:%RDM13%-3f6b-e531-4ae1-%RDM2%%RDM3%&gt; &lt;http://emergent.net/aweb/1.0/relpath&gt; &quot;/manifests/songs_dlc_%guitarnamesix%/dlc_guitar_%guitarnamesix%.json&quot;.
        ///
        ///&lt;urn:uuid:%RDM13%-3f6b-e531-4ae1-%RDM2%%RDM3%&gt; &lt;http://emergent.net/aweb/1.0/canonical&gt; &quot;/manifests/songs_dlc_%guitarnamesix%&quot;.
        ///&lt;urn:uuid:%RDM13%-3f6b-e531-4ae1-%RDM2%%RDM3%&gt; &lt;http://emergent.net/aweb/1.0/tag&gt; &quot;database&quot;.
        ///&lt;urn:uuid [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gn_aggregategraph {
            get {
                return ResourceManager.GetString("gn_aggregategraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Entries&quot;: {
        ///    &quot;%ID1MAJ%&quot;: {
        ///      &quot;Attributes&quot;: {
        ///        &quot;DecorativeInlays&quot;: &quot;urn:application:gamebryo-scenegraph:%guitarnamesix%&quot;,
        ///        &quot;DLC&quot;: true,
        ///        &quot;LocName&quot;: &quot;%guitarname%&quot;,
        ///        &quot;ManifestUrn&quot;: &quot;urn:database:json-db:guitar_%guitarnamesix%&quot;,
        ///        &quot;Name&quot;: &quot;%guitarname%&quot;,
        ///        &quot;PreviewArt&quot;: &quot;urn:image:dds:reward_inlay_%guitarnamesix%&quot;,
        ///        &quot;PersistentID&quot;: &quot;%ID1MAJ%&quot;
        ///      }
        ///    }
        ///  },
        ///  &quot;ModelName&quot;: &quot;RSEnumerable_Guitars&quot;,
        ///  &quot;IterationVersion&quot;: 2,
        ///  &quot;InsertRoo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string guitar_g6 {
            get {
                return ResourceManager.GetString("guitar_g6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;game&gt;
        ///  &lt;entitySet&gt;
        ///    &lt;entity id=&quot;%ID1%&quot; modelName=&quot;RSEnumerable_Guitars&quot; name=&quot;%guitarnamesix%&quot; iterations=&quot;0&quot;&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;Header&quot;&gt;
        ///          &lt;set value=&quot;urn:database:hsan-db:guitars&quot; /&gt;
        ///        &lt;/property&gt;
        ///        &lt;property name=&quot;Manifest&quot;&gt;
        ///          &lt;set value=&quot;urn:database:json-db:guitar_%guitarnamesix%&quot; /&gt;
        ///        &lt;/property&gt;
        ///        &lt;property name=&quot;PreviewArt&quot;&gt;
        ///          &lt;set value=&quot;urn:image:dds:reward_inlay_%guitar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string guitar_g61 {
            get {
                return ResourceManager.GetString("guitar_g61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Entries&quot; : {
        ///        &quot;%ID1MAJ%&quot; : {
        ///           &quot;Attributes&quot; : {
        ///               &quot;DLC&quot; : true,
        ///               &quot;LocName&quot; : &quot;%guitarname%&quot;,
        ///               &quot;ManifestUrn&quot; : &quot;urn:database:json-db:guitar_%guitarnamesix%&quot;,
        ///               &quot;Name&quot; : &quot;%guitarname%&quot;,
        ///               &quot;PersistentID&quot; : &quot;%ID1MAJ%&quot;,
        ///               &quot;PreviewArt&quot; : &quot;urn:image:dds:reward_inlay_%guitarnamesix%&quot;
        ///            }
        ///        }
        ///    },
        ///    &quot;InsertRoot&quot; : &quot;Static.Guitars.Headers&quot;
        ///}.
        /// </summary>
        public static string guitars {
            get {
                return ResourceManager.GetString("guitars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;model name=&quot;RSEnumerable_Guitars&quot; id=&quot;%RDM21%&quot;&gt;
        ///  &lt;trait value=&quot;Active&quot; /&gt;
        ///  &lt;mixin name=&quot;RSEnumerable_Root&quot; id=&quot;%RDM20%&quot; type=&quot;Active&quot; /&gt;
        ///  &lt;property type=&quot;AssetID&quot; name=&quot;DecorativeInlays&quot; id=&quot;%RDM22%&quot;&gt;
        ///    &lt;set value=&quot;&quot; /&gt;
        ///  &lt;/property&gt;
        ///  &lt;property type=&quot;AssetID&quot; name=&quot;PreviewArtSmall&quot; id=&quot;%RDM23%&quot;&gt;
        ///    &lt;set value=&quot;&quot; /&gt;
        ///  &lt;/property&gt;
        ///  &lt;property type=&quot;AssetID&quot; name=&quot;PreviewArtMedium&quot; id=&quot;%RDM24%&quot;&gt;
        ///    &lt;set value=&quot;&quot; /&gt;
        ///  &lt;/property&gt;
        ///  &lt;property type=&quot;Ass [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rsenumerable_guitars {
            get {
                return ResourceManager.GetString("rsenumerable_guitars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;model name=&quot;RSEnumerable_Root&quot; id=&quot;%RDM20%&quot;&gt;
        ///  &lt;trait value=&quot;Active&quot; /&gt;
        ///  &lt;property type=&quot;AssetID&quot; name=&quot;Manifest&quot; id=&quot;%RDM26%&quot;&gt;
        ///    &lt;set value=&quot;&quot; /&gt;
        ///  &lt;/property&gt;
        ///  &lt;property type=&quot;AssetID&quot; name=&quot;Header&quot; id=&quot;%RDM27%&quot;&gt;
        ///    &lt;set value=&quot;&quot; /&gt;
        ///  &lt;/property&gt;
        ///&lt;/model&gt;.
        /// </summary>
        public static string rsenumerable_root {
            get {
                return ResourceManager.GetString("rsenumerable_root", resourceCulture);
            }
        }
    }
}
