// Generated by Xamasoft JSON Class Generator
// Cozy1 Customized Version JSON=>XML=>JSON
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Diagnostics;
using Newtonsoft.Json;

namespace RocksmithToolkitLib.JSON
{
    [JsonObject(MemberSerialization.OptIn)]
    public class Song
    {
        [JsonProperty("Entries")]
        public Entries Entries { get; set; }

        [JsonProperty("ModelName")]
        public string ModelName { get; set; }

        [JsonProperty("IterationVersion")]
        public int IterationVersion { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class ChordTemplate
    {
        [JsonProperty("ChordId")]
        public int ChordId { get; set; }

        [JsonProperty("ChordName")]
        public string ChordName { get; set; }

        [JsonProperty("Fingers")]
        public int[] Fingers { get; set; }

        [JsonProperty("Frets")]
        public int[] Frets { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class PhraseIteration
    {
        [JsonProperty("PhraseIndex")]
        public int PhraseIndex { get; set; }

        [JsonProperty("MaxDifficulty")]
        public int MaxDifficulty { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("StartTime")]
        public double StartTime { get; set; }

        [JsonProperty("EndTime")]
        public double EndTime { get; set; }

        [JsonProperty("MaxScorePerDifficulty")]
        public double[] MaxScorePerDifficulty { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Phras
    {
        [JsonProperty("MaxDifficulty")]
        public int MaxDifficulty { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("IterationCount")]
        public int IterationCount { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Section
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("UIName")]
        public string UIName { get; set; }

        [JsonProperty("Number")]
        public int Number { get; set; }

        [JsonProperty("StartTime")]
        public double StartTime { get; set; }

        [JsonProperty("EndTime")]
        public double EndTime { get; set; }

        [JsonProperty("StartPhraseIterationIndex")]
        public int StartPhraseIterationIndex { get; set; }

        [JsonProperty("EndPhraseIterationIndex")]
        public int EndPhraseIterationIndex { get; set; }

        [JsonProperty("IsSolo")]
        public bool IsSolo { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Attributes
    {
        [JsonProperty("AlbumArt")]
        public string AlbumArt { get; set; }

        [JsonProperty("AlbumName")]
        public string AlbumName { get; set; }

        [JsonProperty("AlbumNameSort")]
        public string AlbumNameSort { get; set; }

        [JsonProperty("ArrangementName")]
        public string ArrangementName { get; set; }

        [JsonProperty("ArtistName")]
        public string ArtistName { get; set; }

        [JsonProperty("ArtistNameSort")]
        public string ArtistNameSort { get; set; }

        [JsonProperty("AssociatedTechniques")]
        public string[] AssociatedTechniques { get; set; }

        [JsonProperty("BarChords")]
        public bool BarChords { get; set; }

        [JsonProperty("Bends")]
        public bool Bends { get; set; }

        [JsonProperty("BinaryVersion")]
        public int BinaryVersion { get; set; }

        [JsonProperty("BlockAsset")]
        public string BlockAsset { get; set; }

        [JsonProperty("ChordTemplates")]
        public ChordTemplate[] ChordTemplates { get; set; }

        [JsonProperty("DISC_DLC_OTHER")]
        public string DISCDLCOTHER { get; set; }

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("DLCPreview")]
        public bool DLCPreview { get; set; }

        [JsonProperty("DoubleStops")]
        public bool DoubleStops { get; set; }

        [JsonProperty("DropDPowerChords")]
        public bool DropDPowerChords { get; set; }

        [JsonProperty("DynamicVisualDensity")]
        public double[] DynamicVisualDensity { get; set; }

        [JsonProperty("EffectChainMultiplayerName")]
        public string EffectChainMultiplayerName { get; set; }

        [JsonProperty("EffectChainName")]
        public string EffectChainName { get; set; }

        [JsonProperty("EventFirstTimeSortOrder")]
        public int EventFirstTimeSortOrder { get; set; }

        [JsonProperty("ExclusiveBuild")]
        public object[] ExclusiveBuild { get; set; }

        [JsonProperty("FifthsAndOctaves")]
        public bool FifthsAndOctaves { get; set; }

        [JsonProperty("ForceUseXML")]
        public bool ForceUseXML { get; set; }

        [JsonProperty("FretHandMutes")]
        public bool FretHandMutes { get; set; }

        [JsonProperty("Genre")]
        public string Genre { get; set; }

        [JsonProperty("Harmonics")]
        public bool Harmonics { get; set; }

        [JsonProperty("HOPOs")]
        public bool HOPOs { get; set; }

        [JsonProperty("InputEvent")]
        public string InputEvent { get; set; }

        [JsonProperty("IsDemoSong")]
        public bool IsDemoSong { get; set; }

        [JsonProperty("IsDLC")]
        public bool IsDLC { get; set; }

        [JsonProperty("LastConversionDateTime")]
        public string LastConversionDateTime { get; set; }

        [JsonProperty("MasterID_PS3")]
        public int MasterIDPS3 { get; set; }

        [JsonProperty("MasterID_Xbox360")]
        public int MasterIDXbox360 { get; set; }

        [JsonProperty("MaxPhraseDifficulty")]
        public int MaxPhraseDifficulty { get; set; }

        [JsonProperty("OpenChords")]
        public bool OpenChords { get; set; }

        [JsonProperty("PalmMutes")]
        public bool PalmMutes { get; set; }

        [JsonProperty("PersistentID")]
        public string PersistentID { get; set; }

        [JsonProperty("PhraseIterations")]
        public PhraseIteration[] PhraseIterations { get; set; }

        [JsonProperty("Phrases")]
        public Phras[] Phrases { get; set; }

        [JsonProperty("PluckedType")]
        public string PluckedType { get; set; }

        [JsonProperty("PowerChords")]
        public bool PowerChords { get; set; }

        [JsonProperty("Prebends")]
        public bool Prebends { get; set; }

        [JsonProperty("RelativeDifficulty")]
        public int RelativeDifficulty { get; set; }

        [JsonProperty("RepresentativeArrangement")]
        public bool RepresentativeArrangement { get; set; }

        [JsonProperty("Score_MaxNotes")]
        public double ScoreMaxNotes { get; set; }

        [JsonProperty("Score_PNV")]
        public double ScorePNV { get; set; }

        [JsonProperty("Sections")]
        public Section[] Sections { get; set; }

        [JsonProperty("Shipping")]
        public bool Shipping { get; set; }

        [JsonProperty("SlapAndPop")]
        public bool SlapAndPop { get; set; }

        [JsonProperty("Slides")]
        public bool Slides { get; set; }

        [JsonProperty("SongAsset")]
        public string SongAsset { get; set; }

        [JsonProperty("SongDifficulty")]
        public double SongDifficulty { get; set; }

        [JsonProperty("SongEvent")]
        public string SongEvent { get; set; }

        [JsonProperty("SongKey")]
        public string SongKey { get; set; }

        [JsonProperty("SongLength")]
        public double SongLength { get; set; }

        [JsonProperty("SongName")]
        public string SongName { get; set; }

        [JsonProperty("SongNameSort")]
        public string SongNameSort { get; set; }

        [JsonProperty("SongPartition")]
        public int SongPartition { get; set; }

        [JsonProperty("SongXml")]
        public string SongXml { get; set; }

        [JsonProperty("SongYear")]
        public int SongYear { get; set; }

        [JsonProperty("Sustain")]
        public bool Sustain { get; set; }

        [JsonProperty("Syncopation")]
        public bool Syncopation { get; set; }

        [JsonProperty("TargetScore")]
        public int TargetScore { get; set; }

        [JsonProperty("ToneUnlockScore")]
        public int ToneUnlockScore { get; set; }

        [JsonProperty("Tremolo")]
        public bool Tremolo { get; set; }

        [JsonProperty("Tuning")]
        public string Tuning { get; set; }

        [JsonProperty("TwoFingerPlucking")]
        public bool TwoFingerPlucking { get; set; }

        [JsonProperty("TwoHandTapping")]
        public bool TwoHandTapping { get; set; }

        [JsonProperty("UnlockKey")]
        public string UnlockKey { get; set; }

        [JsonProperty("Vibrato")]
        public bool Vibrato { get; set; }

        [JsonProperty("VocalsAssetId")]
        public string VocalsAssetId { get; set; }

        [JsonProperty("FirstArrangementInSong")]
        public bool FirstArrangementInSong { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class ChordTemplate2
    {
        [JsonProperty("ChordId")]
        public int ChordId { get; set; }

        [JsonProperty("ChordName")]
        public string ChordName { get; set; }

        [JsonProperty("Fingers")]
        public int[] Fingers { get; set; }

        [JsonProperty("Frets")]
        public int[] Frets { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class PhraseIteration2
    {
        [JsonProperty("PhraseIndex")]
        public int PhraseIndex { get; set; }

        [JsonProperty("MaxDifficulty")]
        public int MaxDifficulty { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("StartTime")]
        public double StartTime { get; set; }

        [JsonProperty("EndTime")]
        public double EndTime { get; set; }

        [JsonProperty("MaxScorePerDifficulty")]
        public double[] MaxScorePerDifficulty { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Phras2
    {
        [JsonProperty("MaxDifficulty")]
        public int MaxDifficulty { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("IterationCount")]
        public int IterationCount { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Section2
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("UIName")]
        public string UIName { get; set; }

        [JsonProperty("Number")]
        public int Number { get; set; }

        [JsonProperty("StartTime")]
        public double StartTime { get; set; }

        [JsonProperty("EndTime")]
        public double EndTime { get; set; }

        [JsonProperty("StartPhraseIterationIndex")]
        public int StartPhraseIterationIndex { get; set; }

        [JsonProperty("EndPhraseIterationIndex")]
        public int EndPhraseIterationIndex { get; set; }

        [JsonProperty("IsSolo")]
        public bool IsSolo { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Attributes2
    {
        [JsonProperty("AlbumArt")]
        public string AlbumArt { get; set; }

        [JsonProperty("AlbumName")]
        public string AlbumName { get; set; }

        [JsonProperty("AlbumNameSort")]
        public string AlbumNameSort { get; set; }

        [JsonProperty("ArrangementName")]
        public string ArrangementName { get; set; }

        [JsonProperty("ArtistName")]
        public string ArtistName { get; set; }

        [JsonProperty("ArtistNameSort")]
        public string ArtistNameSort { get; set; }

        [JsonProperty("AssociatedTechniques")]
        public string[] AssociatedTechniques { get; set; }

        [JsonProperty("BarChords")]
        public bool BarChords { get; set; }

        [JsonProperty("Bends")]
        public bool Bends { get; set; }

        [JsonProperty("BinaryVersion")]
        public int BinaryVersion { get; set; }

        [JsonProperty("BlockAsset")]
        public string BlockAsset { get; set; }

        [JsonProperty("ChordTemplates")]
        public ChordTemplate2[] ChordTemplates { get; set; }

        [JsonProperty("DISC_DLC_OTHER")]
        public string DISCDLCOTHER { get; set; }

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("DLCPreview")]
        public bool DLCPreview { get; set; }

        [JsonProperty("DoubleStops")]
        public bool DoubleStops { get; set; }

        [JsonProperty("DropDPowerChords")]
        public bool DropDPowerChords { get; set; }

        [JsonProperty("DynamicVisualDensity")]
        public double[] DynamicVisualDensity { get; set; }

        [JsonProperty("EffectChainMultiplayerName")]
        public string EffectChainMultiplayerName { get; set; }

        [JsonProperty("EffectChainName")]
        public string EffectChainName { get; set; }

        [JsonProperty("EventFirstTimeSortOrder")]
        public int EventFirstTimeSortOrder { get; set; }

        [JsonProperty("ExclusiveBuild")]
        public object[] ExclusiveBuild { get; set; }

        [JsonProperty("FifthsAndOctaves")]
        public bool FifthsAndOctaves { get; set; }

        [JsonProperty("ForceUseXML")]
        public bool ForceUseXML { get; set; }

        [JsonProperty("FretHandMutes")]
        public bool FretHandMutes { get; set; }

        [JsonProperty("Genre")]
        public string Genre { get; set; }

        [JsonProperty("Harmonics")]
        public bool Harmonics { get; set; }

        [JsonProperty("HOPOs")]
        public bool HOPOs { get; set; }

        [JsonProperty("InputEvent")]
        public string InputEvent { get; set; }

        [JsonProperty("IsDemoSong")]
        public bool IsDemoSong { get; set; }

        [JsonProperty("IsDLC")]
        public bool IsDLC { get; set; }

        [JsonProperty("LastConversionDateTime")]
        public string LastConversionDateTime { get; set; }

        [JsonProperty("MasterID_PS3")]
        public int MasterIDPS3 { get; set; }

        [JsonProperty("MasterID_Xbox360")]
        public int MasterIDXbox360 { get; set; }

        [JsonProperty("MaxPhraseDifficulty")]
        public int MaxPhraseDifficulty { get; set; }

        [JsonProperty("OpenChords")]
        public bool OpenChords { get; set; }

        [JsonProperty("PalmMutes")]
        public bool PalmMutes { get; set; }

        [JsonProperty("PersistentID")]
        public string PersistentID { get; set; }

        [JsonProperty("PhraseIterations")]
        public PhraseIteration2[] PhraseIterations { get; set; }

        [JsonProperty("Phrases")]
        public Phras2[] Phrases { get; set; }

        [JsonProperty("PluckedType")]
        public string PluckedType { get; set; }

        [JsonProperty("PowerChords")]
        public bool PowerChords { get; set; }

        [JsonProperty("Prebends")]
        public bool Prebends { get; set; }

        [JsonProperty("RelativeDifficulty")]
        public int RelativeDifficulty { get; set; }

        [JsonProperty("RepresentativeArrangement")]
        public bool RepresentativeArrangement { get; set; }

        [JsonProperty("Score_MaxNotes")]
        public double ScoreMaxNotes { get; set; }

        [JsonProperty("Score_PNV")]
        public double ScorePNV { get; set; }

        [JsonProperty("Sections")]
        public Section2[] Sections { get; set; }

        [JsonProperty("Shipping")]
        public bool Shipping { get; set; }

        [JsonProperty("SlapAndPop")]
        public bool SlapAndPop { get; set; }

        [JsonProperty("Slides")]
        public bool Slides { get; set; }

        [JsonProperty("SongAsset")]
        public string SongAsset { get; set; }

        [JsonProperty("SongDifficulty")]
        public double SongDifficulty { get; set; }

        [JsonProperty("SongEvent")]
        public string SongEvent { get; set; }

        [JsonProperty("SongKey")]
        public string SongKey { get; set; }

        [JsonProperty("SongLength")]
        public double SongLength { get; set; }

        [JsonProperty("SongName")]
        public string SongName { get; set; }

        [JsonProperty("SongNameSort")]
        public string SongNameSort { get; set; }

        [JsonProperty("SongPartition")]
        public int SongPartition { get; set; }

        [JsonProperty("SongXml")]
        public string SongXml { get; set; }

        [JsonProperty("SongYear")]
        public int SongYear { get; set; }

        [JsonProperty("Sustain")]
        public bool Sustain { get; set; }

        [JsonProperty("Syncopation")]
        public bool Syncopation { get; set; }

        [JsonProperty("TargetScore")]
        public int TargetScore { get; set; }

        [JsonProperty("ToneUnlockScore")]
        public int ToneUnlockScore { get; set; }

        [JsonProperty("Tremolo")]
        public bool Tremolo { get; set; }

        [JsonProperty("Tuning")]
        public string Tuning { get; set; }

        [JsonProperty("TwoFingerPlucking")]
        public bool TwoFingerPlucking { get; set; }

        [JsonProperty("TwoHandTapping")]
        public bool TwoHandTapping { get; set; }

        [JsonProperty("UnlockKey")]
        public string UnlockKey { get; set; }

        [JsonProperty("Vibrato")]
        public bool Vibrato { get; set; }

        [JsonProperty("VocalsAssetId")]
        public string VocalsAssetId { get; set; }

        [JsonProperty("FirstArrangementInSong")]
        public bool FirstArrangementInSong { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Attributes3
    {
        [JsonProperty("AlbumArt")]
        public string AlbumArt { get; set; }

        [JsonProperty("AlbumName")]
        public string AlbumName { get; set; }

        [JsonProperty("AlbumNameSort")]
        public string AlbumNameSort { get; set; }

        [JsonProperty("ArrangementName")]
        public string ArrangementName { get; set; }

        [JsonProperty("ArtistName")]
        public string ArtistName { get; set; }

        [JsonProperty("ArtistNameSort")]
        public string ArtistNameSort { get; set; }

        [JsonProperty("AssociatedTechniques")]
        public object[] AssociatedTechniques { get; set; }

        [JsonProperty("BarChords")]
        public bool BarChords { get; set; }

        [JsonProperty("Bends")]
        public bool Bends { get; set; }

        [JsonProperty("BinaryVersion")]
        public int BinaryVersion { get; set; }

        [JsonProperty("BlockAsset")]
        public string BlockAsset { get; set; }

        [JsonProperty("DISC_DLC_OTHER")]
        public string DISCDLCOTHER { get; set; }

        [JsonProperty("DisplayName")]
        public string DisplayName { get; set; }

        [JsonProperty("DLCPreview")]
        public bool DLCPreview { get; set; }

        [JsonProperty("DoubleStops")]
        public bool DoubleStops { get; set; }

        [JsonProperty("DropDPowerChords")]
        public bool DropDPowerChords { get; set; }

        [JsonProperty("DynamicVisualDensity")]
        public double[] DynamicVisualDensity { get; set; }

        [JsonProperty("EffectChainMultiplayerName")]
        public string EffectChainMultiplayerName { get; set; }

        [JsonProperty("EffectChainName")]
        public string EffectChainName { get; set; }

        [JsonProperty("EventFirstTimeSortOrder")]
        public int EventFirstTimeSortOrder { get; set; }

        [JsonProperty("ExclusiveBuild")]
        public object[] ExclusiveBuild { get; set; }

        [JsonProperty("FifthsAndOctaves")]
        public bool FifthsAndOctaves { get; set; }

        [JsonProperty("ForceUseXML")]
        public bool ForceUseXML { get; set; }

        [JsonProperty("FretHandMutes")]
        public bool FretHandMutes { get; set; }

        [JsonProperty("Genre")]
        public string Genre { get; set; }

        [JsonProperty("Harmonics")]
        public bool Harmonics { get; set; }

        [JsonProperty("HOPOs")]
        public bool HOPOs { get; set; }

        [JsonProperty("InputEvent")]
        public string InputEvent { get; set; }

        [JsonProperty("IsDemoSong")]
        public bool IsDemoSong { get; set; }

        [JsonProperty("IsDLC")]
        public bool IsDLC { get; set; }

        [JsonProperty("MasterID_PS3")]
        public int MasterIDPS3 { get; set; }

        [JsonProperty("MasterID_Xbox360")]
        public int MasterIDXbox360 { get; set; }

        [JsonProperty("OpenChords")]
        public bool OpenChords { get; set; }

        [JsonProperty("PalmMutes")]
        public bool PalmMutes { get; set; }

        [JsonProperty("PersistentID")]
        public string PersistentID { get; set; }

        [JsonProperty("PluckedType")]
        public string PluckedType { get; set; }

        [JsonProperty("PowerChords")]
        public bool PowerChords { get; set; }

        [JsonProperty("Prebends")]
        public bool Prebends { get; set; }

        [JsonProperty("RelativeDifficulty")]
        public int RelativeDifficulty { get; set; }

        [JsonProperty("RepresentativeArrangement")]
        public bool RepresentativeArrangement { get; set; }

        [JsonProperty("Shipping")]
        public bool Shipping { get; set; }

        [JsonProperty("SlapAndPop")]
        public bool SlapAndPop { get; set; }

        [JsonProperty("Slides")]
        public bool Slides { get; set; }

        [JsonProperty("SongAsset")]
        public string SongAsset { get; set; }

        [JsonProperty("SongEvent")]
        public string SongEvent { get; set; }

        [JsonProperty("SongKey")]
        public string SongKey { get; set; }

        [JsonProperty("SongName")]
        public string SongName { get; set; }

        [JsonProperty("SongNameSort")]
        public string SongNameSort { get; set; }

        [JsonProperty("SongXml")]
        public string SongXml { get; set; }

        [JsonProperty("SongYear")]
        public int SongYear { get; set; }

        [JsonProperty("Sustain")]
        public bool Sustain { get; set; }

        [JsonProperty("Syncopation")]
        public bool Syncopation { get; set; }

        [JsonProperty("ToneUnlockScore")]
        public int ToneUnlockScore { get; set; }

        [JsonProperty("Tremolo")]
        public bool Tremolo { get; set; }

        [JsonProperty("Tuning")]
        public string Tuning { get; set; }

        [JsonProperty("TwoFingerPlucking")]
        public bool TwoFingerPlucking { get; set; }

        [JsonProperty("TwoHandTapping")]
        public bool TwoHandTapping { get; set; }

        [JsonProperty("UnlockKey")]
        public string UnlockKey { get; set; }

        [JsonProperty("Vibrato")]
        public bool Vibrato { get; set; }

        [JsonProperty("VocalsAssetId")]
        public string VocalsAssetId { get; set; }

        [JsonProperty("FirstArrangementInSong")]
        public bool FirstArrangementInSong { get; set; }
    }

    // TODO: Fix this

    //[JsonObject(MemberSerialization.OptIn)]
    //public class 3FF4D47BE22E4F0AA94F73E4EED52FDD
    //{
    //    [JsonProperty("Attributes")]
    //    public Attributes Attributes { get; set; }
    //}

    //[JsonObject(MemberSerialization.OptIn)]
    //public class 7B08D9755B0D40CE847488FEE87A6F74
    //{
    //    [JsonProperty("Attributes")]
    //    public Attributes3 Attributes { get; set; }
    //}

    [JsonObject(MemberSerialization.OptIn)]
    public class Entries
    {
        //    [JsonProperty("3FF4D47BE22E4F0AA94F73E4EED52FDD")]
        //    public 3FF4D47BE22E4F0AA94F73E4EED52FDD 3FF4D47BE22E4F0AA94F73E4EED52FDD { get; set; }

        //    [JsonProperty("5C43CA6D36744E33B740B2C9A728A129")]
        //    public 5C43CA6D36744E33B740B2C9A728A129 5C43CA6D36744E33B740B2C9A728A129 { get; set; }

        //    [JsonProperty("7B08D9755B0D40CE847488FEE87A6F74")]
        //    public 7B08D9755B0D40CE847488FEE87A6F74 7B08D9755B0D40CE847488FEE87A6F74 { get; set; }
    }
}
