// Generated by Xamasoft JSON Class Generator
// Cozy1 Customized Version JSON=>XML=>JSON
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace RocksmithToolkitLib.JSON
{
    [JsonObject(MemberSerialization.OptIn)]
    public class Tone
    {
        [JsonProperty("Entries")]
        public Entry[] Entries { get; set; }

        [JsonProperty("ModelName")]
        public string ModelName { get; set; }

        [JsonProperty("IterationVersion")]
        public int IterationVersion { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class KnobValues
    {
        [JsonProperty("Pedal_HolyCow_Reverb")]
        public double PedalHolyCowReverb { get; set; }

        [JsonProperty("Pedal_HolyCow_Mix")]
        public double PedalHolyCowMix { get; set; }

        [JsonProperty("Pedal_AnalogueDelay_WetDry")]
        public double? PedalAnalogueDelayWetDry { get; set; }

        [JsonProperty("Pedal_AnalogueDelay_Tone")]
        public double? PedalAnalogueDelayTone { get; set; }

        [JsonProperty("Pedal_AnalogueDelay_Time")]
        public double? PedalAnalogueDelayTime { get; set; }

        [JsonProperty("Pedal_AnalogueDelay_Feedback")]
        public double? PedalAnalogueDelayFeedback { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class PostPedal3
    {
        [JsonProperty("PedalKey")]
        public string PedalKey { get; set; }

        [JsonProperty("KnobValues")]
        public KnobValues KnobValues { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class KnobValues2
    {
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Cabinet
    {
        [JsonProperty("PedalKey")]
        public string PedalKey { get; set; }

        [JsonProperty("KnobValues")]
        public KnobValues2 KnobValues { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class KnobValues3
    {
        [JsonProperty("Pedal_ModDelay_Time")]
        public double PedalModDelayTime { get; set; }

        [JsonProperty("Pedal_ModDelay_Feedback")]
        public double PedalModDelayFeedback { get; set; }

        [JsonProperty("Pedal_ModDelay_Depth")]
        public double PedalModDelayDepth { get; set; }

        [JsonProperty("Pedal_ModDelay_Frequency")]
        public double PedalModDelayFrequency { get; set; }

        [JsonProperty("Pedal_ModDelay_WetDry")]
        public double PedalModDelayWetDry { get; set; }

        [JsonProperty("Pedal_EQ7_1600")]
        public double? PedalEQ71600 { get; set; }

        [JsonProperty("Pedal_EQ7_3200")]
        public double? PedalEQ73200 { get; set; }

        [JsonProperty("Pedal_EQ7_6400")]
        public double? PedalEQ76400 { get; set; }

        [JsonProperty("Pedal_EQ7_100")]
        public double? PedalEQ7100 { get; set; }

        [JsonProperty("Pedal_EQ7_200")]
        public double? PedalEQ7200 { get; set; }

        [JsonProperty("Pedal_EQ7_400")]
        public double? PedalEQ7400 { get; set; }

        [JsonProperty("Pedal_EQ7_800")]
        public double? PedalEQ7800 { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class LoopPedal3
    {
        [JsonProperty("PedalKey")]
        public string PedalKey { get; set; }

        [JsonProperty("KnobValues")]
        public KnobValues3 KnobValues { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class KnobValues4
    {
        [JsonProperty("Amp_SoloTenor_Bass")]
        public double AmpSoloTenorBass { get; set; }

        [JsonProperty("Amp_SoloTenor_Treble")]
        public double AmpSoloTenorTreble { get; set; }

        [JsonProperty("Amp_SoloTenor_Volume")]
        public double AmpSoloTenorVolume { get; set; }

        [JsonProperty("Amp_Ranger65_Gain")]
        public double? AmpRanger65Gain { get; set; }

        [JsonProperty("Amp_Ranger65_Bass")]
        public double? AmpRanger65Bass { get; set; }

        [JsonProperty("Amp_Ranger65_Mid")]
        public double? AmpRanger65Mid { get; set; }

        [JsonProperty("Amp_Ranger65_Treble")]
        public double? AmpRanger65Treble { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Amp
    {
        [JsonProperty("PedalKey")]
        public string PedalKey { get; set; }

        [JsonProperty("KnobValues")]
        public KnobValues4 KnobValues { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class KnobValues5
    {
        [JsonProperty("Pedal_CustomDrive_Drive")]
        public double PedalCustomDriveDrive { get; set; }

        [JsonProperty("Pedal_CustomDrive_Tone")]
        public double PedalCustomDriveTone { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class PrePedal3
    {
        [JsonProperty("PedalKey")]
        public string PedalKey { get; set; }

        [JsonProperty("KnobValues")]
        public KnobValues5 KnobValues { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class PedalList
    {
        [JsonProperty("PostPedal3")]
        public PostPedal3 PostPedal3 { get; set; }

        [JsonProperty("Cabinet")]
        public Cabinet Cabinet { get; set; }

        [JsonProperty("LoopPedal3")]
        public LoopPedal3 LoopPedal3 { get; set; }

        [JsonProperty("Amp")]
        public Amp Amp { get; set; }

        [JsonProperty("PrePedal3")]
        public PrePedal3 PrePedal3 { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Entry
    {
        [JsonProperty("BlockAsset")]
        public string BlockAsset { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("ExclusiveBuild")]
        public object[] ExclusiveBuild { get; set; }

        [JsonProperty("IsDLC")]
        public bool IsDLC { get; set; }

        [JsonProperty("IsPreviewOnlyItem")]
        public bool IsPreviewOnlyItem { get; set; }

        [JsonProperty("Key")]
        public string Key { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("PedalList")]
        public PedalList PedalList { get; set; }

        [JsonProperty("PersistentID")]
        public string PersistentID { get; set; }

        [JsonProperty("UnlockKey")]
        public string UnlockKey { get; set; }

        [JsonProperty("Volume")]
        public double Volume { get; set; }
    }


}
