//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class song : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string titleField;
    
    private string arrangementField;
    
    private string partField;
    
    private string artistField;
    
    private string offsetField;
    
    private string songLengthField;
    
    private string lastConversionDateTimeField;
    
    private songPhrases[] phrasesField;
    
    private songPhraseIterations[] phraseIterationsField;
    
    private songLinkedDiffs[] linkedDiffsField;
    
    private songPhraseProperties[] phrasePropertiesField;
    
    private songChordTemplates[] chordTemplatesField;
    
    private songFretHandMuteTemplates[] fretHandMuteTemplatesField;
    
    private songEbeats[] ebeatsField;
    
    private songSections[] sectionsField;
    
    private songEvents[] eventsField;
    
    private songLevels[] levelsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
            this.RaisePropertyChanged("title");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arrangement {
        get {
            return this.arrangementField;
        }
        set {
            this.arrangementField = value;
            this.RaisePropertyChanged("arrangement");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
            this.RaisePropertyChanged("part");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string artist {
        get {
            return this.artistField;
        }
        set {
            this.artistField = value;
            this.RaisePropertyChanged("artist");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
            this.RaisePropertyChanged("offset");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string songLength {
        get {
            return this.songLengthField;
        }
        set {
            this.songLengthField = value;
            this.RaisePropertyChanged("songLength");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lastConversionDateTime {
        get {
            return this.lastConversionDateTimeField;
        }
        set {
            this.lastConversionDateTimeField = value;
            this.RaisePropertyChanged("lastConversionDateTime");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phrases", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songPhrases[] phrases {
        get {
            return this.phrasesField;
        }
        set {
            this.phrasesField = value;
            this.RaisePropertyChanged("phrases");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phraseIterations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songPhraseIterations[] phraseIterations {
        get {
            return this.phraseIterationsField;
        }
        set {
            this.phraseIterationsField = value;
            this.RaisePropertyChanged("phraseIterations");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("linkedDiffs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLinkedDiffs[] linkedDiffs {
        get {
            return this.linkedDiffsField;
        }
        set {
            this.linkedDiffsField = value;
            this.RaisePropertyChanged("linkedDiffs");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phraseProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songPhraseProperties[] phraseProperties {
        get {
            return this.phrasePropertiesField;
        }
        set {
            this.phrasePropertiesField = value;
            this.RaisePropertyChanged("phraseProperties");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chordTemplates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songChordTemplates[] chordTemplates {
        get {
            return this.chordTemplatesField;
        }
        set {
            this.chordTemplatesField = value;
            this.RaisePropertyChanged("chordTemplates");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fretHandMuteTemplates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songFretHandMuteTemplates[] fretHandMuteTemplates {
        get {
            return this.fretHandMuteTemplatesField;
        }
        set {
            this.fretHandMuteTemplatesField = value;
            this.RaisePropertyChanged("fretHandMuteTemplates");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ebeats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songEbeats[] ebeats {
        get {
            return this.ebeatsField;
        }
        set {
            this.ebeatsField = value;
            this.RaisePropertyChanged("ebeats");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sections", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songSections[] sections {
        get {
            return this.sectionsField;
        }
        set {
            this.sectionsField = value;
            this.RaisePropertyChanged("sections");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("events", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songEvents[] events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
            this.RaisePropertyChanged("events");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("levels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevels[] levels {
        get {
            return this.levelsField;
        }
        set {
            this.levelsField = value;
            this.RaisePropertyChanged("levels");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songPhrases : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songPhrasesPhrase[] phraseField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phrase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songPhrasesPhrase[] phrase {
        get {
            return this.phraseField;
        }
        set {
            this.phraseField = value;
            this.RaisePropertyChanged("phrase");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songPhrasesPhrase : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string disparityField;
    
    private string ignoreField;
    
    private string maxDifficultyField;
    
    private string nameField;
    
    private string soloField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disparity {
        get {
            return this.disparityField;
        }
        set {
            this.disparityField = value;
            this.RaisePropertyChanged("disparity");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ignore {
        get {
            return this.ignoreField;
        }
        set {
            this.ignoreField = value;
            this.RaisePropertyChanged("ignore");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxDifficulty {
        get {
            return this.maxDifficultyField;
        }
        set {
            this.maxDifficultyField = value;
            this.RaisePropertyChanged("maxDifficulty");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string solo {
        get {
            return this.soloField;
        }
        set {
            this.soloField = value;
            this.RaisePropertyChanged("solo");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songPhraseIterations : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songPhraseIterationsPhraseIteration[] phraseIterationField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phraseIteration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songPhraseIterationsPhraseIteration[] phraseIteration {
        get {
            return this.phraseIterationField;
        }
        set {
            this.phraseIterationField = value;
            this.RaisePropertyChanged("phraseIteration");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songPhraseIterationsPhraseIteration : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string timeField;
    
    private string phraseIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
            this.RaisePropertyChanged("time");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phraseId {
        get {
            return this.phraseIdField;
        }
        set {
            this.phraseIdField = value;
            this.RaisePropertyChanged("phraseId");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLinkedDiffs : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songPhraseProperties : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songPhrasePropertiesPhraseProperty[] phrasePropertyField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("phraseProperty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songPhrasePropertiesPhraseProperty[] phraseProperty {
        get {
            return this.phrasePropertyField;
        }
        set {
            this.phrasePropertyField = value;
            this.RaisePropertyChanged("phraseProperty");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songPhrasePropertiesPhraseProperty : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string difficultyField;
    
    private string emptyField;
    
    private string levelJumpField;
    
    private string phraseIdField;
    
    private string redundantField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string difficulty {
        get {
            return this.difficultyField;
        }
        set {
            this.difficultyField = value;
            this.RaisePropertyChanged("difficulty");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string empty {
        get {
            return this.emptyField;
        }
        set {
            this.emptyField = value;
            this.RaisePropertyChanged("empty");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string levelJump {
        get {
            return this.levelJumpField;
        }
        set {
            this.levelJumpField = value;
            this.RaisePropertyChanged("levelJump");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phraseId {
        get {
            return this.phraseIdField;
        }
        set {
            this.phraseIdField = value;
            this.RaisePropertyChanged("phraseId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string redundant {
        get {
            return this.redundantField;
        }
        set {
            this.redundantField = value;
            this.RaisePropertyChanged("redundant");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songChordTemplates : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songChordTemplatesChordTemplate[] chordTemplateField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chordTemplate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songChordTemplatesChordTemplate[] chordTemplate {
        get {
            return this.chordTemplateField;
        }
        set {
            this.chordTemplateField = value;
            this.RaisePropertyChanged("chordTemplate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songChordTemplatesChordTemplate : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string chordNameField;
    
    private string finger0Field;
    
    private string finger1Field;
    
    private string finger2Field;
    
    private string finger3Field;
    
    private string finger4Field;
    
    private string finger5Field;
    
    private string fret0Field;
    
    private string fret1Field;
    
    private string fret2Field;
    
    private string fret3Field;
    
    private string fret4Field;
    
    private string fret5Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chordName {
        get {
            return this.chordNameField;
        }
        set {
            this.chordNameField = value;
            this.RaisePropertyChanged("chordName");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finger0 {
        get {
            return this.finger0Field;
        }
        set {
            this.finger0Field = value;
            this.RaisePropertyChanged("finger0");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finger1 {
        get {
            return this.finger1Field;
        }
        set {
            this.finger1Field = value;
            this.RaisePropertyChanged("finger1");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finger2 {
        get {
            return this.finger2Field;
        }
        set {
            this.finger2Field = value;
            this.RaisePropertyChanged("finger2");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finger3 {
        get {
            return this.finger3Field;
        }
        set {
            this.finger3Field = value;
            this.RaisePropertyChanged("finger3");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finger4 {
        get {
            return this.finger4Field;
        }
        set {
            this.finger4Field = value;
            this.RaisePropertyChanged("finger4");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string finger5 {
        get {
            return this.finger5Field;
        }
        set {
            this.finger5Field = value;
            this.RaisePropertyChanged("finger5");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret0 {
        get {
            return this.fret0Field;
        }
        set {
            this.fret0Field = value;
            this.RaisePropertyChanged("fret0");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret1 {
        get {
            return this.fret1Field;
        }
        set {
            this.fret1Field = value;
            this.RaisePropertyChanged("fret1");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret2 {
        get {
            return this.fret2Field;
        }
        set {
            this.fret2Field = value;
            this.RaisePropertyChanged("fret2");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret3 {
        get {
            return this.fret3Field;
        }
        set {
            this.fret3Field = value;
            this.RaisePropertyChanged("fret3");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret4 {
        get {
            return this.fret4Field;
        }
        set {
            this.fret4Field = value;
            this.RaisePropertyChanged("fret4");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret5 {
        get {
            return this.fret5Field;
        }
        set {
            this.fret5Field = value;
            this.RaisePropertyChanged("fret5");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songFretHandMuteTemplates : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songEbeats : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songEbeatsEbeat[] ebeatField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ebeat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songEbeatsEbeat[] ebeat {
        get {
            return this.ebeatField;
        }
        set {
            this.ebeatField = value;
            this.RaisePropertyChanged("ebeat");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songEbeatsEbeat : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string timeField;
    
    private string measureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
            this.RaisePropertyChanged("time");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string measure {
        get {
            return this.measureField;
        }
        set {
            this.measureField = value;
            this.RaisePropertyChanged("measure");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songSections : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songSectionsSection[] sectionField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("section", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songSectionsSection[] section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
            this.RaisePropertyChanged("section");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songSectionsSection : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private string numberField;
    
    private string startTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
            this.RaisePropertyChanged("number");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
            this.RaisePropertyChanged("startTime");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songEvents : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songEventsEvent[] eventField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songEventsEvent[] @event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
            this.RaisePropertyChanged("event");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songEventsEvent : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string timeField;
    
    private string codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
            this.RaisePropertyChanged("time");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
            this.RaisePropertyChanged("code");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevels : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songLevelsLevel[] levelField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("level", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevel[] level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
            this.RaisePropertyChanged("level");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevel : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songLevelsLevelNotes[] notesField;
    
    private songLevelsLevelChords[] chordsField;
    
    private songLevelsLevelFretHandMutes[] fretHandMutesField;
    
    private songLevelsLevelAnchors[] anchorsField;
    
    private songLevelsLevelHandShapes[] handShapesField;
    
    private string difficultyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelNotes[] notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
            this.RaisePropertyChanged("notes");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelChords[] chords {
        get {
            return this.chordsField;
        }
        set {
            this.chordsField = value;
            this.RaisePropertyChanged("chords");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fretHandMutes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelFretHandMutes[] fretHandMutes {
        get {
            return this.fretHandMutesField;
        }
        set {
            this.fretHandMutesField = value;
            this.RaisePropertyChanged("fretHandMutes");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("anchors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelAnchors[] anchors {
        get {
            return this.anchorsField;
        }
        set {
            this.anchorsField = value;
            this.RaisePropertyChanged("anchors");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handShapes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelHandShapes[] handShapes {
        get {
            return this.handShapesField;
        }
        set {
            this.handShapesField = value;
            this.RaisePropertyChanged("handShapes");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string difficulty {
        get {
            return this.difficultyField;
        }
        set {
            this.difficultyField = value;
            this.RaisePropertyChanged("difficulty");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelNotes : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songLevelsLevelNotesNote[] noteField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelNotesNote[] note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
            this.RaisePropertyChanged("note");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelNotesNote : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string timeField;
    
    private string bendField;
    
    private string fretField;
    
    private string hammerOnField;
    
    private string harmonicField;
    
    private string hopoField;
    
    private string ignoreField;
    
    private string palmMuteField;
    
    private string pullOffField;
    
    private string slideToField;
    
    private string stringField;
    
    private string sustainField;
    
    private string tremoloField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
            this.RaisePropertyChanged("time");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bend {
        get {
            return this.bendField;
        }
        set {
            this.bendField = value;
            this.RaisePropertyChanged("bend");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret {
        get {
            return this.fretField;
        }
        set {
            this.fretField = value;
            this.RaisePropertyChanged("fret");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hammerOn {
        get {
            return this.hammerOnField;
        }
        set {
            this.hammerOnField = value;
            this.RaisePropertyChanged("hammerOn");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string harmonic {
        get {
            return this.harmonicField;
        }
        set {
            this.harmonicField = value;
            this.RaisePropertyChanged("harmonic");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hopo {
        get {
            return this.hopoField;
        }
        set {
            this.hopoField = value;
            this.RaisePropertyChanged("hopo");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ignore {
        get {
            return this.ignoreField;
        }
        set {
            this.ignoreField = value;
            this.RaisePropertyChanged("ignore");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string palmMute {
        get {
            return this.palmMuteField;
        }
        set {
            this.palmMuteField = value;
            this.RaisePropertyChanged("palmMute");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pullOff {
        get {
            return this.pullOffField;
        }
        set {
            this.pullOffField = value;
            this.RaisePropertyChanged("pullOff");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slideTo {
        get {
            return this.slideToField;
        }
        set {
            this.slideToField = value;
            this.RaisePropertyChanged("slideTo");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @string {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
            this.RaisePropertyChanged("string");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sustain {
        get {
            return this.sustainField;
        }
        set {
            this.sustainField = value;
            this.RaisePropertyChanged("sustain");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tremolo {
        get {
            return this.tremoloField;
        }
        set {
            this.tremoloField = value;
            this.RaisePropertyChanged("tremolo");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelChords : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songLevelsLevelChordsChord[] chordField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelChordsChord[] chord {
        get {
            return this.chordField;
        }
        set {
            this.chordField = value;
            this.RaisePropertyChanged("chord");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelChordsChord : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string timeField;
    
    private string chordIdField;
    
    private string highDensityField;
    
    private string ignoreField;
    
    private string strumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
            this.RaisePropertyChanged("time");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chordId {
        get {
            return this.chordIdField;
        }
        set {
            this.chordIdField = value;
            this.RaisePropertyChanged("chordId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string highDensity {
        get {
            return this.highDensityField;
        }
        set {
            this.highDensityField = value;
            this.RaisePropertyChanged("highDensity");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ignore {
        get {
            return this.ignoreField;
        }
        set {
            this.ignoreField = value;
            this.RaisePropertyChanged("ignore");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string strum {
        get {
            return this.strumField;
        }
        set {
            this.strumField = value;
            this.RaisePropertyChanged("strum");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelFretHandMutes : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelAnchors : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songLevelsLevelAnchorsAnchor[] anchorField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("anchor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelAnchorsAnchor[] anchor {
        get {
            return this.anchorField;
        }
        set {
            this.anchorField = value;
            this.RaisePropertyChanged("anchor");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelAnchorsAnchor : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string timeField;
    
    private string fretField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
            this.RaisePropertyChanged("time");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fret {
        get {
            return this.fretField;
        }
        set {
            this.fretField = value;
            this.RaisePropertyChanged("fret");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelHandShapes : object, System.ComponentModel.INotifyPropertyChanged {
    
    private songLevelsLevelHandShapesHandShape[] handShapeField;
    
    private string countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handShape", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public songLevelsLevelHandShapesHandShape[] handShape {
        get {
            return this.handShapeField;
        }
        set {
            this.handShapeField = value;
            this.RaisePropertyChanged("handShape");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
            this.RaisePropertyChanged("count");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class songLevelsLevelHandShapesHandShape : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string chordIdField;
    
    private string endTimeField;
    
    private string startTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chordId {
        get {
            return this.chordIdField;
        }
        set {
            this.chordIdField = value;
            this.RaisePropertyChanged("chordId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
            this.RaisePropertyChanged("endTime");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
            this.RaisePropertyChanged("startTime");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet : object, System.ComponentModel.INotifyPropertyChanged {
    
    private song[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("song")]
    public song[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
            this.RaisePropertyChanged("Items");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
