//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocksmithToolkitLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocksmithToolkitLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] albumart {
            get {
                object obj = ResourceManager.GetObject("albumart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] albumart2014_128 {
            get {
                object obj = ResourceManager.GetObject("albumart2014_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] albumart2014_256 {
            get {
                object obj = ResourceManager.GetObject("albumart2014_256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] albumart2014_64 {
            get {
                object obj = ResourceManager.GetObject("albumart2014_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] cgm_default_icon {
            get {
                object obj = ResourceManager.GetObject("cgm_default_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] cgm_default_inlay {
            get {
                object obj = ResourceManager.GetObject("cgm_default_inlay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Console_soundbank {
            get {
                object obj = ResourceManager.GetObject("Console_soundbank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] PC_soundbank {
            get {
                object obj = ResourceManager.GetObject("PC_soundbank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] pedals {
            get {
                object obj = ResourceManager.GetObject("pedals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] pedals2014 {
            get {
                object obj = ResourceManager.GetObject("pedals2014", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] rsenumerable_guitar {
            get {
                object obj = ResourceManager.GetObject("rsenumerable_guitar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] rsenumerable_root {
            get {
                object obj = ResourceManager.GetObject("rsenumerable_root", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] rsenumerable_song {
            get {
                object obj = ResourceManager.GetObject("rsenumerable_song", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Icon TreeViewOfd {
            get {
                object obj = ResourceManager.GetObject("TreeViewOfd", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] VOCALS_RS2 {
            get {
                object obj = ResourceManager.GetObject("VOCALS_RS2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XBox360_DLC_image {
            get {
                object obj = ResourceManager.GetObject("XBox360_DLC_image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XBox360_DLC_image2014 {
            get {
                object obj = ResourceManager.GetObject("XBox360_DLC_image2014", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XBox360_KV {
            get {
                object obj = ResourceManager.GetObject("XBox360_KV", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
