//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocksmithToolkitLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocksmithToolkitLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] albumart {
            get {
                object obj = ResourceManager.GetObject("albumart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] albumart2014_128 {
            get {
                object obj = ResourceManager.GetObject("albumart2014_128", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] albumart2014_256 {
            get {
                object obj = ResourceManager.GetObject("albumart2014_256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] albumart2014_64 {
            get {
                object obj = ResourceManager.GetObject("albumart2014_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Console_soundbank {
            get {
                object obj = ResourceManager.GetObject("Console_soundbank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Console2014_soundbank {
            get {
                object obj = ResourceManager.GetObject("Console2014_soundbank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Console2014_soundbank_preview {
            get {
                object obj = ResourceManager.GetObject("Console2014_soundbank_preview", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PC_RS2014_vocal_symbol {
            get {
                object obj = ResourceManager.GetObject("PC_RS2014_vocal_symbol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PC_soundbank {
            get {
                object obj = ResourceManager.GetObject("PC_soundbank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PC2014_soundbank {
            get {
                object obj = ResourceManager.GetObject("PC2014_soundbank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PC2014_soundbank_preview {
            get {
                object obj = ResourceManager.GetObject("PC2014_soundbank_preview", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pedals {
            get {
                object obj = ResourceManager.GetObject("pedals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pedals2014 {
            get {
                object obj = ResourceManager.GetObject("pedals2014", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsenumerable_root {
            get {
                object obj = ResourceManager.GetObject("rsenumerable_root", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsenumerable_song {
            get {
                object obj = ResourceManager.GetObject("rsenumerable_song", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;song version=&quot;7&quot;&gt;
        ///  &lt;title&gt;&lt;/title&gt;
        ///  &lt;arrangement&gt;PART VOCAL&lt;/arrangement&gt;
        ///  &lt;part&gt;1&lt;/part&gt;
        ///  &lt;offset&gt;0.000&lt;/offset&gt;
        ///  &lt;centOffset&gt;0&lt;/centOffset&gt;
        ///  &lt;songLength&gt;0.000&lt;/songLength&gt;
        ///  &lt;lastConversionDateTime&gt;11-25-13 6:47&lt;/lastConversionDateTime&gt;
        ///  &lt;startBeat&gt;0.000&lt;/startBeat&gt;
        ///  &lt;averageTempo&gt;180.000&lt;/averageTempo&gt;
        ///  &lt;tuning string0=&quot;0&quot; string1=&quot;0&quot; string2=&quot;0&quot; string3=&quot;0&quot; string4=&quot;0&quot; string5=&quot;0&quot; /&gt;
        ///  &lt;capo&gt;0&lt;/capo&gt;
        ///  &lt;artistName&gt;&lt;/artistName&gt;
        ///  &lt;artistName [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VOCALS_RS2 {
            get {
                return ResourceManager.GetString("VOCALS_RS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XBox360_DLC_image {
            get {
                object obj = ResourceManager.GetObject("XBox360_DLC_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XBox360_DLC_image2014 {
            get {
                object obj = ResourceManager.GetObject("XBox360_DLC_image2014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XBox360_KV {
            get {
                object obj = ResourceManager.GetObject("XBox360_KV", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
